"""Differential test: the Python calibration against the TypeScript it was ported from.

The fixtures were generated by running the reference implementation
(`/workspace/aichart/src/lib/strategies/calibration.ts`) and committing its
output. Reading the TypeScript and writing "the same thing" in Python is exactly
how a port drifts: the code works, the numbers differ, and nobody notices until
a confidence figure is quietly wrong.

The bootstrap makes this sharper than most ports. It draws 2000 x n samples from
a seeded PRNG, so a single divergence in the random stream — one unsigned shift
handled as signed — changes every draw after it while still producing perfectly
plausible-looking numbers.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from app.services.strategies.calibration import calibrate_win_rate, wilson_score_interval

pytestmark = pytest.mark.no_db

_GOLDEN = json.loads(
    (Path(__file__).parent / "fixtures" / "golden" / "strategy_calibration.json").read_text()
)

#: Exact for the discrete fields, 1e-9 relative for the derived floats. Anything
#: needing a wider tolerance is a porting bug, not a tolerance case
#: (docs/PORTING.md).
_TOL = 1e-9


def _case_id(case: dict[str, Any]) -> str:
    inp = case.get("input", case)
    return f"{inp.get('wins')}of{inp.get('samples')}"


@pytest.mark.parametrize("case", _GOLDEN["wilson"], ids=_case_id)
def test_wilson_matches_the_reference(case: dict[str, Any]) -> None:
    low, high = wilson_score_interval(case["wins"], case["samples"], case["z"])
    assert low == pytest.approx(case["low"], rel=_TOL, abs=_TOL)
    assert high == pytest.approx(case["high"], rel=_TOL, abs=_TOL)


@pytest.mark.parametrize("case", _GOLDEN["bootstrap"], ids=_case_id)
def test_calibration_matches_the_reference(case: dict[str, Any]) -> None:
    inp = case["input"]
    kwargs: dict[str, Any] = {"wins": inp["wins"], "samples": inp["samples"]}
    if "iterations" in inp:
        kwargs["iterations"] = inp["iterations"]
    if "confidenceLevel" in inp:
        kwargs["confidence_level"] = inp["confidenceLevel"]
    if "seed" in inp:
        kwargs["seed"] = inp["seed"]
    if "minTradesForCalibration" in inp:
        kwargs["min_trades"] = inp["minTradesForCalibration"]

    result = calibrate_win_rate(**kwargs)
    want = case["output"]

    # Exact for everything discrete: method, counts, sufficiency, seed. A port
    # that lands in the wrong branch produces numbers that are individually
    # reasonable, so the branch itself has to be asserted.
    assert result.method == want["method"]
    assert result.samples == want["samples"]
    assert result.iterations == want["iterations"]
    assert result.statistically_sufficient == want["statisticallySufficient"]
    assert result.seed == want["seed"]

    assert result.win_rate == pytest.approx(want["winRate"], rel=_TOL, abs=_TOL)
    assert result.confidence_low == pytest.approx(want["confidenceLow"], rel=_TOL, abs=_TOL)
    assert result.confidence_high == pytest.approx(want["confidenceHigh"], rel=_TOL, abs=_TOL)


def test_a_sample_of_one_does_not_report_certainty() -> None:
    """The reason the Wilson branch exists at all.

    An IID bootstrap of a single observation resamples that observation every
    time, so it returns a zero-width interval — perfect confidence from one
    trade. That is not a conservative failure mode, it is the most dangerous
    one, because the output reads as certainty.
    """
    result = calibrate_win_rate(wins=1, samples=1)
    assert result.method == "wilson"
    assert result.statistically_sufficient is False
    assert result.width > 0.5


def test_no_observations_is_the_whole_range_not_a_coin_flip() -> None:
    result = calibrate_win_rate(wins=0, samples=0)
    assert (result.confidence_low, result.confidence_high) == (0.0, 1.0)
    assert result.statistically_sufficient is False


def test_the_same_record_always_gives_the_same_confidence() -> None:
    """An unseeded bootstrap makes the number unfalsifiable."""
    a = calibrate_win_rate(wins=52, samples=100)
    b = calibrate_win_rate(wins=52, samples=100)
    assert a == b
