#!/usr/bin/env bash
# Build a staging .env file from environment variables.
# NEVER prints secret values. Hard-enforces practice OANDA + execution off.
set -euo pipefail

OUT="${1:?Usage: generate_staging_env.sh <output-path>}"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

# --- Broker policy (non-negotiable) ---
ENV_VAL="${OANDA_ENVIRONMENT:-practice}"
if [[ "${ENV_VAL}" != "practice" ]]; then
  fail "OANDA_ENVIRONMENT must be 'practice' (got '${ENV_VAL}'). Refusing to deploy."
fi

EXEC_VAL="${OANDA_EXECUTION:-false}"
case "${EXEC_VAL,,}" in
  1|true|yes|on|enabled)
    fail "OANDA_EXECUTION is enabled ('${EXEC_VAL}'). Refusing to deploy."
    ;;
esac

# Required runtime secrets for a usable staging stack
: "${OANDA_API_TOKEN:?Missing OANDA_API_TOKEN}"
: "${OANDA_ACCOUNT_ID:?Missing OANDA_ACCOUNT_ID}"
: "${ANTHROPIC_API_KEY:?Missing ANTHROPIC_API_KEY}"
: "${OPENAI_API_KEY:?Missing OPENAI_API_KEY}"
: "${SECRET_KEY:?Missing SECRET_KEY}"

PUBLIC_URL="${PUBLIC_URL:-https://staging.leovee.lork.cloud}"
CORS_ORIGINS="${CORS_ORIGINS:-https://staging.leovee.lork.cloud}"
LEOVEE_DOMAIN="${LEOVEE_DOMAIN:-staging.leovee.lork.cloud}"
ACME_EMAIL="${ACME_EMAIL:-admin@lork.cloud}"

DATABASE_URL="${DATABASE_URL:-postgresql+asyncpg://leovee_app:leovee_app@postgres:5432/leovee}"
DATABASE_MIGRATION_URL="${DATABASE_MIGRATION_URL:-postgresql+asyncpg://leovee:leovee@postgres:5432/leovee}"
REDIS_URL="${REDIS_URL:-redis://redis:6379/0}"

# Decouple platform-secret encryption from SECRET_KEY: mint a dedicated key when the
# operator did not supply one (openssl is the documented way to make these — the same
# `openssl rand -hex 32` recipe SECRET_KEY uses). Command substitution keeps the value
# off stdout. NOTE: a regenerated key cannot decrypt secrets written under a previous
# one, so set ENCRYPTION_KEY explicitly for a persistent staging DB across redeploys.
ENCRYPTION_KEY="${ENCRYPTION_KEY:-$(openssl rand -hex 32)}"

umask 077
# Write without `set -x` and without echoing values.
cat >"${OUT}" <<EOF
# Generated by scripts/generate_staging_env.sh — do not commit
ENVIRONMENT=staging
SECRET_KEY=${SECRET_KEY}
# Behind Caddy/nginx: trust X-Forwarded-For so per-client rate limits work.
TRUST_PROXY_HEADERS=true
# Dev impersonation bypass — must stay false; startup refuses to boot if true.
DEV_AUTH_BYPASS=false
PUBLIC_URL=${PUBLIC_URL}
CORS_ORIGINS=${CORS_ORIGINS}
LEOVEE_DOMAIN=${LEOVEE_DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

DATABASE_URL=${DATABASE_URL}
DATABASE_MIGRATION_URL=${DATABASE_MIGRATION_URL}
REDIS_URL=${REDIS_URL}

ENCRYPTION_KEY=${ENCRYPTION_KEY}
KMS_PROVIDER=local

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}

OANDA_API_TOKEN=${OANDA_API_TOKEN}
OANDA_ACCOUNT_ID=${OANDA_ACCOUNT_ID}
OANDA_ENVIRONMENT=practice
OANDA_EXECUTION=false

FINNHUB_API_KEY=${FINNHUB_API_KEY:-}
RESEND_API_KEY=${RESEND_API_KEY:-}
EMAIL_FROM=${EMAIL_FROM:-notifications@leovee.lork.cloud}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
BILLING_PROVIDER=${BILLING_PROVIDER:-manual}

SENTRY_DSN=${SENTRY_DSN:-}
LOG_LEVEL=${LOG_LEVEL:-INFO}
METRICS_BEARER_TOKEN=${METRICS_BEARER_TOKEN:-}

ARQ_MAX_JOBS=10
VITE_API_URL=
EOF

chmod 600 "${OUT}"
echo "[env] wrote staging .env to ${OUT} (secrets redacted; OANDA_ENVIRONMENT=practice; OANDA_EXECUTION=false)"
