#!/usr/bin/env bash
# Build a PRODUCTION .env file from environment variables.
#
# Difference from generate_staging_env.sh: this emits ENVIRONMENT=production
# (which arms the stronger startup guards) and treats the OANDA and LLM keys as
# OPTIONAL — they are platform secrets an admin enters in the panel at runtime
# (see app/services/platform_secrets.py :: MANAGED_SECRET_KEYS), encrypted in
# the DB and applied without a redeploy. What MUST live in this file is the
# bootstrap minimum the process needs before the DB/admin panel is reachable:
# SECRET_KEY (the encryption parent is pinned from it at boot), the DB/Redis
# URLs, the proxy/domain topology, and ENCRYPTION_KEY.
#
# NEVER prints secret values. Hard-enforces practice OANDA + execution off.
set -euo pipefail

OUT="${1:?Usage: generate_prod_env.sh <output-path>}"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

# --- Broker policy (non-negotiable, even when OANDA is set later via the panel) ---
ENV_VAL="${OANDA_ENVIRONMENT:-practice}"
if [[ "${ENV_VAL}" != "practice" ]]; then
  fail "OANDA_ENVIRONMENT must be 'practice' (got '${ENV_VAL}'). Refusing to deploy."
fi

EXEC_VAL="${OANDA_EXECUTION:-false}"
case "${EXEC_VAL,,}" in
  1 | true | yes | on | enabled)
    fail "OANDA_EXECUTION is enabled ('${EXEC_VAL}'). Refusing to deploy."
    ;;
esac

# --- Bootstrap minimum (must exist before the app/admin panel is reachable) ---
: "${SECRET_KEY:?Missing SECRET_KEY (openssl rand -hex 32)}"
# ENCRYPTION_KEY is required for production, not minted: a fresh key cannot
# decrypt platform secrets written under a previous one, so a random value per
# run would orphan every admin-entered OANDA/LLM key on the next redeploy.
: "${ENCRYPTION_KEY:?Missing ENCRYPTION_KEY (openssl rand -hex 32) — set it once and keep it durable}"
# No localhost fallback in production: a wrong domain silently breaks CORS/TLS.
: "${LEOVEE_DOMAIN:?Missing LEOVEE_DOMAIN (e.g. app.leovee.example.com)}"
: "${ACME_EMAIL:?Missing ACME_EMAIL (for ACME/TLS certificate issuance)}"

PUBLIC_URL="${PUBLIC_URL:-https://${LEOVEE_DOMAIN}}"
CORS_ORIGINS="${CORS_ORIGINS:-${PUBLIC_URL}}"

DATABASE_URL="${DATABASE_URL:-postgresql+asyncpg://leovee_app:leovee_app@postgres:5432/leovee}"
DATABASE_MIGRATION_URL="${DATABASE_MIGRATION_URL:-postgresql+asyncpg://leovee:leovee@postgres:5432/leovee}"
REDIS_URL="${REDIS_URL:-redis://redis:6379/0}"

# The RLS contract: the runtime role must be leovee_app, never a superuser. The
# app re-checks this at boot, but catching a superuser DATABASE_URL here fails
# the deploy before a single request is served.
if [[ "${DATABASE_URL}" == *"://postgres:"* || "${DATABASE_URL}" == *"://leovee:"* ]]; then
  fail "DATABASE_URL must authenticate as 'leovee_app' (got a privileged role). Use DATABASE_MIGRATION_URL for the migrate step."
fi

# Pull the two passwords back out of the URLs so the rest of the stack can be
# configured from one source of truth. Format: scheme://user:password@host:port/db
url_password() {
  local url="$1"
  local userinfo="${url#*://}"
  userinfo="${userinfo%%@*}"
  [[ "${userinfo}" == *:* ]] || return 1
  printf '%s' "${userinfo#*:}"
}

POSTGRES_PASSWORD="$(url_password "${DATABASE_MIGRATION_URL}")" ||
  fail "DATABASE_MIGRATION_URL has no password. Expected postgresql+asyncpg://leovee:<pw>@postgres:5432/leovee"
LEOVEE_APP_DB_PASSWORD="$(url_password "${DATABASE_URL}")" ||
  fail "DATABASE_URL has no password. Expected postgresql+asyncpg://leovee_app:<pw>@postgres:5432/leovee"

# The compose defaults ('leovee' for the owner role, and the 'leovee_app'
# literal that migration 007 assigns) are published in this repository. They are
# fine for local dev, where nothing is reachable; in production they are a known
# credential on the shared compose network, which every container — api, worker,
# mcp, and anything added later — can reach. Refuse them here rather than let a
# deploy inherit them silently.
if [[ "${POSTGRES_PASSWORD}" == "leovee" ]]; then
  fail "DATABASE_MIGRATION_URL uses the built-in 'leovee' password. Generate one: openssl rand -hex 24"
fi
if [[ "${LEOVEE_APP_DB_PASSWORD}" == "leovee_app" ]]; then
  fail "DATABASE_URL uses the built-in 'leovee_app' password. Generate one: openssl rand -hex 24"
fi
if [[ "${POSTGRES_PASSWORD}" == "${LEOVEE_APP_DB_PASSWORD}" ]]; then
  fail "The owner and application roles must not share a password — that erases the privilege split RLS depends on."
fi

umask 077
# Write without `set -x` and without echoing values. OANDA/LLM keys are written
# only when the operator supplied them; otherwise they are left blank for the
# admin panel to fill at runtime.
cat >"${OUT}" <<EOF
# Generated by scripts/generate_prod_env.sh — do not commit
ENVIRONMENT=production
SECRET_KEY=${SECRET_KEY}
# Behind Caddy/nginx: trust X-Forwarded-For so per-client rate limits work.
TRUST_PROXY_HEADERS=true
# Dev impersonation bypass — must stay false; startup refuses to boot if true.
DEV_AUTH_BYPASS=false
PUBLIC_URL=${PUBLIC_URL}
CORS_ORIGINS=${CORS_ORIGINS}
LEOVEE_DOMAIN=${LEOVEE_DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

DATABASE_URL=${DATABASE_URL}
DATABASE_MIGRATION_URL=${DATABASE_MIGRATION_URL}
REDIS_URL=${REDIS_URL}

# Consumed by docker-compose.yml to initialise the postgres owner role, and by
# deploy_prod_vps.sh to re-assign the leovee_app password after migrations (007
# hardcodes the literal 'leovee_app', so it must be reset on every upgrade).
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
LEOVEE_APP_DB_PASSWORD=${LEOVEE_APP_DB_PASSWORD}

ENCRYPTION_KEY=${ENCRYPTION_KEY}
KMS_PROVIDER=local

# LLM + OANDA keys are OPTIONAL here — enter them in the admin panel
# (Settings → Secrets) after first boot; they apply immediately, encrypted in
# the DB. Values supplied at generate time are written through as a convenience.
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}

OANDA_API_TOKEN=${OANDA_API_TOKEN:-}
OANDA_ACCOUNT_ID=${OANDA_ACCOUNT_ID:-}
OANDA_ENVIRONMENT=practice
OANDA_EXECUTION=false

FINNHUB_API_KEY=${FINNHUB_API_KEY:-}
RESEND_API_KEY=${RESEND_API_KEY:-}
EMAIL_FROM=${EMAIL_FROM:-notifications@${LEOVEE_DOMAIN}}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
BILLING_PROVIDER=${BILLING_PROVIDER:-manual}

SENTRY_DSN=${SENTRY_DSN:-}
LOG_LEVEL=${LOG_LEVEL:-INFO}
# Required in production for GET /metrics (Authorization: Bearer …).
METRICS_BEARER_TOKEN=${METRICS_BEARER_TOKEN:-}

ARQ_MAX_JOBS=${ARQ_MAX_JOBS:-10}
VITE_API_URL=
EOF

chmod 600 "${OUT}"
echo "[env] wrote production .env to ${OUT} (secrets redacted; ENVIRONMENT=production; OANDA practice, execution off)"
echo "[env] OANDA/LLM keys left to the admin panel unless supplied at generate time."
